[package]
name = "nips"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boxfnonce = "0.1.1"
comrak = "0.23.0"
include_dir = { version = "0.7.3", features = ["glob", "metadata"] }
markdown = "1.0.0-alpha.18"
markdown2html-converter = "1.1.12"
tinyfiledialogs = "3.9.1"
urlencoding = "2.1.3"
webview-sys = { version = "0.6.2", path = "webview-sys" }
