#!/usr/bin/env bash


type -P gnostr-reflog >/dev/null || cargo install gnostr-bins
type -P gnostr-get-relays >/dev/null || cargo install gnostr-bins

some_path=$PWD
REPO=$(basename $some_path)
PARENT_REPO=$(basename $(dirname $some_path))
##GRANDPARENT_REPO=$(basename $(dirname $(dirname $some_path)))



IS_REPO=$(git rev-parse --is-inside-work-tree)
#exit
#echo $IS_REPO
if $IS_REPO;then
#echo 1 $IS_REPO=$REPO
REPO=$(basename $some_path);
else
#echo 2 $IS_REPO=$REPO
REPO=$(basename $(dirname $some_path));
fi

BRANCH=`git rev-parse --abbrev-ref HEAD` #&& echo $BRANCH

GIT_ORIGIN=$(git config --get remote.origin.url)
#echo $GIT_ORIGIN
#exit;

#non public/slow/unfriendly relays get included
#strip them out here
RELAYS=$(gnostr-get-relays -s \
| sed 's/wss:\/\/relay.oldcity-bitcoiners.info//g' \
| sed 's/wss:\/\/relay.damus.io//g' \
| sed 's/wss:\/\/relay.damus.io//g' \
| sed 's/wss:\/\/relay.damus.io//g' \
| sed 's/wss:\/\/relay.damus.io//g' \
| sed 's/wss:\/\/ragnar-relay.com//g' \
| sed 's/wss:\/\/nostr.slothy.win//g' \
| sed 's/wss:\/\/nostr-relay.schnitzel.world//g' \
| sed 's/wss:\/\/nostr-pub.wellorder.net//g' \
| sed 's/wss:\/\/relay.stoner.com//g' \
| sed 's/wss:\/\/ragnar-relay.com//g' \
| sed 's/wss:\/\/nostr.inosta.cc//g' \
| sed 's/wss:\/\/nos.lol/wss:\/\/e.nos.lol/g' \
)
echo $RELAYS

RELAY=${1:-wss://e.nos.lol}
#echo $RELAY
POW=${2:-12}
echo $POW
GNOSTR_WEEBLE=$(gnostr-weeble)
WEEBLE=${3:-$GNOSTR_WEEBLE}
echo $WEEBLE
BLOCK=${4:-$(gnostr-blockheight)}
echo $BLOCK
WOBBLE=${5:-$(gnostr-wobble)}
echo $WOBBLE
count=0;
new_count=0;
INIT_COMMIT=$(git rev-list --all --max-parents=0)
#echo $INIT_COMMIT;#exit
##git log -1 --skip 2 --pretty=format:"%h"
##git rev-parse --short=256 HEAD~2
#exit
## n=`printf '%016s' "$(git rev-parse --short=4 HEAD~2)"`
#n=`printf '%064s' "$(git rev-parse HEAD~0)"`
#echo $n
## exit

## branch=master
## for commit in $(git rev-list $branch)
## do
##     ## if git ls-tree --name-only -r $commit | grep -q '\.hbm\.xml$'; then
##     if git ls-tree --name-only -r $commit; then
## 
##         ##echo $commit
##         exit 0
##     fi
## done
## exit;

## var=$((var+1))
## ((var=var+1))
## ((var+=1))
## ((var++))

#count=0
for commit_hash in $(git rev-list master);do

padded_commit_hash=`printf '%064s' "$commit_hash"`
#echo $padded_commit_hash
#exit
#echo $commit_hash
count=$((count+1))
done
#exit
export COUNT=$count
#exit

new_count=0
for commit_hash in $(gnostr-reflog);do

for relay in $(gnostr-get-relays -s);do

#echo $commit_hash
padded_commit_hash=`printf '%064s' "$commit_hash"`
#echo $padded_commit_hash
export NEW_COUNT=$new_count
#n=`printf '%064s' "$(git rev-parse HEAD~$count)"`
echo $n
gnostr --sec $padded_commit_hash \
--pow $POW \
--tag relay $relay \
--tag repo $REPO \
--tag branch $BRANCH \
--tag origin $GIT_ORIGIN \
--tag weeble $WEEBLE \
--tag weeble $WEEBLE \
--tag block $BLOCK \
--tag wobble $WOBBLE \
--tag commit $commit_hash \
--content "$(git show $commit_hash || exit)" | gnostr-post-event --relay $relay || echo "$commit_hash failed!"
if [[ "$commit_hash" == "$INIT_COMMIT" ]]; then
exit;
fi
new_count=$((new_count+1))
#echo $count & wait
#echo $new_count & wait
#exit
done
done
exit;
