#!/usr/bin/env bash

for doc in $(ls docs);do echo docs/$doc;git commit docs/$doc -m "docs/$doc";done
for doc in $(ls     );do echo docs/$doc;git commit      $doc -m "     $doc";done

count=0;
new_count=0;
INIT_COMMIT=$(git rev-list --all --max-parents=0)
#echo $INIT_COMMIT;#exit
##git log -1 --skip 2 --pretty=format:"%h"
##git rev-parse --short=256 HEAD~2

## n=`printf '%016s' "$(git rev-parse --short=4 HEAD~2)"`
#n=`printf '%064s' "$(git rev-parse HEAD~0)"`
echo $n
## exit

## branch=master
## for commit in $(git rev-list $branch)
## do
##     ## if git ls-tree --name-only -r $commit | grep -q '\.hbm\.xml$'; then
##     if git ls-tree --name-only -r $commit; then
## 
##         ##echo $commit
##         exit 0
##     fi
## done
## exit;

## var=$((var+1))
## ((var=var+1))
## ((var+=1))
## ((var++))

#count=0
for commit_hash in $(git rev-list master);do

padded_commit_hash=`printf '%064s' "$commit_hash"`
#echo $padded_commit_hash
#exit
#echo $commit_hash
count=$((count+1))
done
#exit
export COUNT=$count
#exit

#new_count = 0
for commit_hash in $(gnostr-reflog);do
echo $commit_hash
padded_commit_hash=`printf '%064s' "$commit_hash"`
echo $padded_commit_hash
export NEW_COUNT=$new_count
#n=`printf '%064s' "$(git rev-parse HEAD~$count)"`
#echo $n
gnostr --sec $padded_commit_hash -t $padded_commit_hash --tag nip_commit $commit_hash --content "$(git show $commit_hash || exit)" | gnostr-post-event --relay wss://e.nos.lol || true
##echo $commit_hash;
	#for commit_padded_hash in $(gnostr-reflog -p);do
	##echo $commit_padded_hash;
	#	gnostr --sec $commit_padded_hash --content "$(git show $commit_hash)"
	#done
if [[ "$commit_hash" == "$INIT_COMMIT" ]]; then
exit;
fi
new_count=$((new_count+1))
#echo $count & wait
#echo $new_count & wait
#exit
done
exit;
