name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: rustc -V
      run: rustc -V
    - name: cargo -V
      run: cargo -V
    - name: Build
      run: cat Cargo.toml && cargo build --verbose
    - name: Run tests
      run: cat Cargo.toml && cargo test --verbose
